import Link from "next/link";
import { Icon } from "@/components/open-daycare";

function AuthLogo({ inverse = false, showName = true }: { inverse?: boolean; showName?: boolean }) {
  return <div className="flex items-center gap-3"><span className={`flex size-[46px] items-center justify-center rounded-[14px] ${inverse ? "bg-white/20" : "bg-linear-to-br from-[#f8c3a8] to-[#f2937a] shadow-lg shadow-[#ee8164]/25"}`}><Icon name="sun" className="size-[26px] text-white" /></span>{showName && <span className={`font-display text-[21px] font-semibold tracking-wide ${inverse ? "text-white" : "text-ink"}`}>OpenDayCare</span>}</div>;
}

function Field({ label, type = "text", defaultValue, placeholder, className = "" }: { label: string; type?: "email" | "password" | "text"; defaultValue?: string; placeholder?: string; className?: string }) {
  return <label className="mb-[18px] block"><span className="mb-2 block text-xs font-extrabold tracking-[0.07em] text-muted">{label}</span><input type={type} defaultValue={defaultValue} placeholder={placeholder} className={`w-full rounded-[14px] border-[1.5px] border-[#eadfd0] bg-white px-4 py-[13px] text-[15px] text-ink outline-none placeholder:text-[#b6a99b] ${className}`} /></label>;
}

export function LoginScreen() {
  return <main className="grid min-h-screen bg-[#fbf4ec] lg:grid-cols-[1.05fr_1fr]">
    <section className="relative hidden overflow-hidden bg-linear-[155deg] from-[#f6a98e] via-[#f2937a] to-[#ec7e62] p-[56px_60px] text-white lg:flex lg:flex-col lg:justify-between">
      <span className="absolute -right-[120px] -top-[140px] size-[420px] rounded-full bg-white/12" /><span className="absolute -bottom-[110px] -left-20 size-[300px] rounded-full bg-white/10" />
      <div className="relative"><AuthLogo inverse /></div>
      <div className="relative"><h1 className="mb-[18px] font-display text-[42px] leading-[1.12] font-semibold">El día de cada niño,<br />compartido con su familia.</h1><p className="max-w-[430px] text-[17px] leading-relaxed text-white/90">Publicá momentos, gestioná las salas y mantené a las familias cerca, desde un solo lugar.</p></div>
      <p className="relative text-sm text-white/90">Guardería Sala Soles</p>
    </section>
    <section className="flex items-center justify-center px-5 py-10 sm:p-10"><div className="w-full max-w-[392px]"><h1 className="mb-1.5 font-display text-[30px] font-semibold text-ink">Iniciar sesión</h1><p className="mb-7 text-[15px] text-muted">Ingresá para ver el día de hoy.</p><Field label="EMAIL" type="email" defaultValue="caro@opendaycare.com" /><Field label="CONTRASEÑA" type="password" placeholder="••••••••" /><button type="button" className="mb-5 block w-full text-right text-[13.5px] font-bold text-[#c5503a]">¿Olvidaste tu contraseña?</button><Link href="/" className="block w-full rounded-[15px] bg-linear-to-b from-[#f4977e] to-[#ee8164] px-4 py-[15px] text-center text-base font-extrabold text-white shadow-lg shadow-[#ee8164]/35">Iniciar sesión</Link><p className="mt-6 text-center text-[14.5px] text-muted">¿Te invitó la guardería? <Link href="/activate" className="font-extrabold text-[#c5503a]">Activá tu cuenta</Link></p></div></section>
  </main>;
}

export function ActivateScreen() {
  return <main className="flex min-h-screen items-center justify-center bg-[#fbf4ec] px-5 py-10 sm:p-10"><section className="w-full max-w-[440px]"><div className="mb-[22px]"><AuthLogo showName={false} /></div><h1 className="mb-2 font-display text-[32px] leading-[1.15] font-semibold text-ink">Bienvenida a OpenDayCare</h1><p className="mb-[26px] text-[15.5px] leading-relaxed text-muted">Te invitaron a seguir el día de tu hijo. Creá tu contraseña para activar la cuenta.</p><div className="mb-[22px] flex items-center gap-[14px] rounded-2xl border-[1.5px] border-[#eadfd0] bg-white p-[14px_16px]"><span className="flex size-11 shrink-0 items-center justify-center rounded-full bg-[#a9d9e8] font-display text-[19px] font-semibold text-[#1f7a93]">M</span><div><p className="text-[13px] text-muted">Te invitaron a seguir a</p><p className="font-display text-[17px] font-semibold text-ink">Mateo · Sala Soles</p></div></div><Field label="CÓDIGO DE INVITACIÓN" defaultValue="7K4P9" className="font-display text-lg font-bold tracking-[3px]" /><Field label="EMAIL" type="email" defaultValue="lucia.fernandez@gmail.com" /><Field label="CREAR CONTRASEÑA" type="password" defaultValue="contraseña" className="border-[#f2a78e]" /><div className="mb-6 flex items-start gap-3 rounded-[14px] bg-[#fbf1d6] p-[14px_16px]"><span aria-hidden="true" className="mt-px flex size-6 shrink-0 items-center justify-center rounded-lg bg-[#5fb97e] text-white"><svg className="size-[15px]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="m20 6-11 11-5-5" /></svg></span><p className="text-sm leading-[1.45] text-[#8a7234]">Autorizo a la guardería a tomar y compartir fotos de mi hijo dentro de la app.</p></div><button type="button" className="w-full rounded-[15px] bg-linear-to-b from-[#f4977e] to-[#ee8164] px-4 py-[15px] text-center text-base font-extrabold text-white shadow-lg shadow-[#ee8164]/35">Activar mi cuenta</button><p className="mt-[22px] text-center text-[14.5px] text-muted">¿Ya tenés cuenta? <Link href="/login" className="font-extrabold text-[#c5503a]">Iniciar sesión</Link></p></section></main>;
}
